name: tagged-release

on:
  push:
    tags:
      - "release-*"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v4
    - name: install depends
      run: |
        sudo apt update
        sudo apt install -y libevent-dev libmbedtls-dev zlib1g-dev
    - name: Build
      run: |
        mkdir release
        make USE_CRYPTO_MBEDTLS=true ENABLE_STATIC=true
        mv redsocks2 release/redsocks2-`arch`-${{github.ref_name}}
    - name: Release
      uses: softprops/action-gh-release@v2
      with:
        files: release/*
